name: foodchain_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # Peticiones HTTP a la API
  http: ^1.3.0

  # Guardar datos localmente (ej: token JWT del login)
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas recomendadas de buenas prácticas
  flutter_lints: ^6.0.0

flutter:
  # Incluye los iconos de Material Design
  uses-material-design: true

  # Para agregar imágenes:
  # assets:
  #   - images/

  # Para agregar fuentes personalizadas:
  # fonts:
  #   - family: MiFuente
  #     fonts:
  #       - asset: fonts/MiFuente-Regular.ttf